services:
  app:
    image: zakupki
    build: .

    depends_on:
      rabbitmq:
        condition: service_healthy

    networks:
      - zakupki

  rabbitmq:
    image: rabbitmq:alpine

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
    networks:
      - zakupki

    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 10s
      timeout: 20s
      retries: 3

networks:
  zakupki:
